---

- hosts: all
  become: yes
  tasks:

  - name: update repository index
    shell: yum makecache # equivalently run the 'apt-get update', it only downloads the index files
    when: ansible_distribution in ["Debian", "Ubuntu", "CentOS"]


  - name: install the latest version of Apache package
    yum:
      name: httpd
      state: latest
    when: ansible_distribution == "CentOS" and ansible_distribution_version == "7.9"


  - name: Install Remi Repository
    yum:
      name: https://rpms.remirepo.net/enterprise/remi-release-7.rpm
      state: present
    when: ansible_distribution == "CentOS"


  - name: install php
    yum:
      enablerepo: "remi,remi-php80"
      name:
         - php
         - php-common
         - php-cli
         - php-gd
         - php-curl #You can add or remove PHP extensions according to your choice
         - php-mysqlnd
         - php-fpm
         - php-mysqli
      state: latest
    when: ansible_distribution == "CentOS"
