---

- hosts: all
  become: yes
  tasks:

  - name: update repository index
    yum:
      name: "*"
      update_cache: yes # equivalently run the 'apt-get update', it only downloads the index files
      #state: latest # equivalently run 'apt-get ugrade', it downloads the latest versions packages of the installed packages


  - name: install the latest version of Apache package
    yum:
      name: httpd
      state: absent


  - name: Install Remi Repository
    yum:
      name: https://rpms.remirepo.net/enterprise/remi-release-7.rpm
      state: present


  - name: install php
    yum:
      enablerepo: "remi,remi-php80"
      name:
         - php
         - php-common
         - php-cli
         - php-gd
         - php-curl #You can add or remove PHP extensions according to your choice
         - php-mysqlnd
         - php-fpm
         - php-mysqli
      state: latest
